language: python
python:
- 3.7
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: BenjaminHabert
  password:
    secure: k8lIFHRJ7crR66rqzXqEJI0mJzpKnjaanu6eyJ5/ZuTxzwBuG/ggFL0oMH4yX+KUnNmw1U2FWPn6l9ygCKrfQ5RLB4j4bGbZupCjthV2GgBlJC/NWweTBIO1oOFusM+Iji5GMJ7iiYqRtncQx5Btk4GkBG+fkBr99E1R7Mvxs0zftzu+SrsHclla42/fbZ6wlLp/GzjGuzwACbF1WLiwBWyy4r5yXJ109g9U8irF8HCbuWTNuKMUvn0v7JZVDDV0dbNTwdQbuJBhY1aR1PvIhOAwzY3+QkOvjz6fC2QfuMtmUr/ph29UIE0BL85/E/a/D5MFv8VvTJ87bOAW38z5fCWG3Nz6q2pPmWIP7FBcOT2pLiA+ucNN1Isvn3XfYAw3upZkd0zO6b4FJ9txJSdX/5bvi14sroWtE6gg2oWMsbzdlX7oKjHJS69mvao74bwgUmkibAfna1lgyoaV1PHqoUN8wgeT11pvYSmMpG1uqtIyjoEUp/EVvlBGWG3U+CJBzrNublRP2c2XwA+/I/oWfVvdMW/7Tvv9XfOqs1o6Xwd/+NDE4uGdSOVpRgikvYuOn7J0BaujHZM/gwGPD4C4iLuhIyfCklyoWuVnznot7ulgrdoZHoJKziSi/z5MnIsn7Fn7JFEsqt+ra+uEHi6k2njFEQGc2PCHJqJPTQc7tZE=
  on:
    tags: true
    repo: Quantmetry/pipeasy-spark
    python: 3.6
